name: build-ios
#on:
#  schedule:
#    - cron: '0 0 * * *'
on:
  push:
    branches:
      - master
env:
  QT_VERSION: 6.5.3
jobs:
  build:
    name: Build
    runs-on: macos-12
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: call cmake -G -h
        run: cmake -G -h
      - name: install qt for desktop
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          dir: ${{ github.workspace }}
          version: ${{ env.QT_VERSION }}
          modules: 'qtcharts qtwebsockets'
      - name: install qt for ios
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          host: 'mac'
          target: 'ios'
          arch: 'ios'
          dir: ${{ github.workspace }}
          version:  ${{ env.QT_VERSION }}
      - name: generate for ios
        run: |
          ${{ github.workspace }}/Qt/${{env.QT_VERSION}}/ios/bin/qt-cmake -G "Xcode" -S . -B "build/ios" \
          -DCMAKE_BUILD_TYPE=Release \
          -DQT_HOST_PATH:PATH="${{ github.workspace }}\Qt\${{env.QT_VERSION}}\macos"
      - name: build for ios
        run: |
          cmake --build "build/ios" --config Release --target StringAssistant
          tree build/ios
